# https://github.com/isunjn/serene/blob/latest/config.example.toml

base_url = "https://kei.network"
title = "aptenodytes"
description = "[->+<]"
default_language = "zh_CN"
theme = "serene"
output_dir = "public"
compile_sass = true
minify_html = true
build_search_index = false
generate_feeds = false
feed_filenames = ["feed.xml"]
taxonomies = [{ name = "tags" }]

[markdown]
highlight_code = true
highlight_theme = "css"
extra_syntaxes_and_themes = ["highlight_themes"]
highlight_themes_css = [
  { theme = "serene-light", filename = "hl-light.css" },
  { theme = "serene-dark", filename = "hl-dark.css" },
]
render_emoji = false
external_links_target_blank = true
external_links_no_follow = true
external_links_no_referrer = true
smart_punctuation = false

[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"

# =============================================================================

[extra]

sections = [
  { name = "关于我", path = "/about", is_external = false },
  { name = "#entry", path = "/tags/entry", is_external = false },
  { name = "#try-catch", path = "/tags/try-catch", is_external = false },
]
blog_section_path = "/posts"

back_link_text = "aptenodytes::super"
force_theme = false # false | "light" | "dark"

footer_copyright = "/cc-by-sa-4.0/ surviving twenty twenty-five"
footer_credits = false

not_found_error_text = 'puts("404");exit();'
not_found_recover_text = "← aptenodytes"

reaction = false
reaction_align = "right" # "left" | "center" | "right"
reaction_endpoint = "https://example.com/api/reaction"
